### ISSUE TITLE
Issue 01

### ISSUE THREAD

**Issue by eyupcimen** [mucitpilot/arduinoprojects#2]
Kardeş bir mailin birseyin yok mu :)  sana ulaşmak icin issue mi acmak lazım illa ki :) Ne bilim Linkldn profili olur birsey olur

**Comment by mucitpilot** [comment]
Merhaba, buyurun mail bu :)
12 Ara 2020 Cmt, saat 01:30 tarihinde Eyup Cimen <notifications@github.com>
şunu yazdı:

**Comment by eyupcimen** [comment]
Ahahah eyvallah :) Demekki buradan ulasacagiz sana :)
